### PR TITLE
qualcommax: ipq60xx: add support for JDCloud AX1800 Pro

### PR DESCRIPTION
**Pull request by breeze303**
Specifications:
  SoC:     Qualcomm IPQ6000
  RAM:     512 MiB
  Flash:   64 GiB EMMC
  ETH:     Qualcomm QCA8075
  WLAN1:   2.4GHz 802.11b/g/n/ax 2x2
  WLAN2:   5GHz 802.11a/n/ac/ax 2x2
  Button:  Reset, Switch
  USB:     1x 3.0

Install via uboot web failsafe:
  Push the reset button for 5 seconds, then use broswer
  to access http://192.168.1.1, and upload factory.ubi.

Afterwards upgrade can use sysupgrade image.

The official review of openwrt is extremely slow, so I'm PR'ing it to you in the hope that you can use it.

### CODE REVIEW

**Comment by Doanduy09** [comment]
Thank you very much for supporting jdc ax1800 pro, hope you support ax6600 as well.

**Comment by Doanduy09** [comment]
I have full jdc ax1800 pro but it still has an error, please help me. Thank you

**Comment by jokubasver** [comment]
> I have full jdc ax1800 pro but it still has an error, please help me. Thank you Screenshot (495)

There's a bit more that's needed to get NSS working on ipq60xx. Take a look at my branch here: https://github.com/jokubasver/openwrt-ipq/commits/qualcommax-6.x-nss-wifi/

**Comment by Doanduy09** [comment]
I have successfully built jdc ax1800 pro but when flashing it, I can't access 192.168.1.1, lost ip, please help me fix it, thank you

**Pull request closed without merging**
